<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Sku</th>
                <th>Products</th>
                <th>Qty</th>
                <th>Tax</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody class="item-tbody">

            </tbody>
        </table>
    </div>
</div>
