<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Sku</th>
                <th>Products</th>
                <th>Qty</th>
                <th>Tax</th>
                <th>Price</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody class="item-tbody">
            <tr>
                <td colspan="2">Item Quantity</td>
                <td>0
                </td><td>Discount</td>
                <td></td>
            </tr>
            <tr>
                <td colspan="2">Item</td>
                <td>0
                </td><td colspan="2">Subtotal</td>
                <td >0
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
