<?php

/**
 * Created by PhpStorm.
 * User: SMART
 * Date: 9/11/2015
 * Time: 4:26 PM
 */
class SM_XPos_Block_Adminhtml_XPos extends  Mage_Core_Block_Template
{
    public function __construct()
    {
        $this->setTemplate('example.phtml');
        parent::__construct(); // TODO: Change the autogenerated stub
//        $block = Mage::app()->getLayout()->getBlock('root');

//        $childBlockNameCollection=$block ->_sortedChildren;
//        echo "<pre>";
//        print_r($childBlockNameCollection);
//        echo "</pre>";
    }

}