<div class="row">
    <?php foreach ($products as $product): ?>
        <div class="col-sm-6 col-md-3 hero-feature">
            <div class="thumbnail">
                <img alt="" src="<?php echo $product['image'] ?>"/>

                <div class="caption">
                    <h6>
                        <?php echo $product['name'] ?>
                    </h6>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>