<div class="panel-heading">
    <table class="panel-title">
        <tbody>
        <tr class="col-lg-12">
            <td class="col-lg-4">Product</td>
            <td class="col-lg-8">
                <form class="search-product">
                    <input type="text" class="search-product form-control" placeholder="Search">
                </form>
            </td>
        </tr>
        </tbody>
    </table>

</div>