<div class="modal fade" id="modal-customer-selector">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <?php echo $this->getChildHtml('search');?>
            </div>

            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>