<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 ">
            <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 text-capitalize">
                <div class="panel panel-primary">
                    <?php
                    echo($this->getChildHtml('items'));
                    echo $this->getChildHtml('items_grid');
                    ?>

                </div>
            </div>

            <div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 ">
                <?php echo($this->getChildHtml('products')); ?>
            </div>

        </div>
    </div>

</div>
